---
stages:
  - build
  - promote

build:image:
  stage: build
  image: quay.io/podman/stable
  script:
    - podman build --tag "$CI_REGISTRY_IMAGE" --file "${CI_PROJECT_DIR}/Dockerfile" $CI_PROJECT_DIR
    - podman push --creds "${CI_REGISTRY_USER}:${CI_JOB_TOKEN}" "$CI_REGISTRY_IMAGE" "docker://${CI_REGISTRY_IMAGE}"
  only:
    - master

promote:image:
  stage: promote
  image: quay.io/containers/skopeo
  script:
    - skopeo copy --src-creds "${CI_REGISTRY_USER}:${CI_JOB_TOKEN}" --dest-creds "${PROMOTE_USER}:${PROMOTE_PASS}" "docker://${CI_REGISTRY_IMAGE}:latest" "docker://${PROMOTE_IMAGE}:latest"
  variables:
    GIT_STRATEGY: none
  only:
    refs:
      - master
    variables:
      - $PROMOTE_USER
      - $PROMOTE_PASS
      - $PROMOTE_REGISTRY
      - $PROMOTE_IMAGE
